version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/1.sql"
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-network

  app:
    build:
      context: node
    working_dir: /usr/src/app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - nginx-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
